name: test

world: 
  name: MinicraftWorld

guide:
  name: SketchGuide

model: 
  name: ModularModel
  actor:
    type: discrete
    n_hidden: [128]
    ret_bias: -3
  controller:
    type: sketch
  critic:
    type: linear

objective:
  discount: 0.9
  action_hcost: 0.001
  ret_hcost: 0.
  step_size: 0.001
  n_train_batch: 2000

trainer: 
  name: CurriculumTrainer
  max_rollout_len: 100
  n_update: 100
  n_rollout_batch: 100
  parallel: 4
