name: test

world: 
  name: ShurdlurnWorld
  train_fold: train
  test_fold: val

guide:
  name: SketchGuide

model: 
  name: ReprModel
  intrinsic_bonus: 0
  actor:
    type: discrete
    n_hidden: [128, 128]
    ret_bias: -3
  controller:
    type: att
    n_hidden: 128
    n_embed: 64
    update: discrete
    gumbel: true
  critic:
    type: linear

objective:
  discount: 0.9
  entropy_bonus: 0.01
  step_size: 0.001
  n_train_batch: 2000

trainer: 
  name: CurriculumTrainer
  max_rollout_len: 100
  n_update: 200
  n_rollout_batch: 100
  parallel: 4
  log_each_task: false
