name: train
train: true
eval: true
load: train
#name: eval
#train: false
#load: train
#eval: true

world: 
  name: ShurdlurnWorld
  train_fold: train
  test_fold: val
  #n_train: 1000
  n_test: 20

guide:
  name: SketchGuide

model: 
  name: ReprModel
  intrinsic_bonus: 0
  actor:
    type: discrete
    n_hidden: [128, 128]
    ret_bias: -3
  controller:
    type: att
    n_hidden: 128
    n_embed: 64
    update: discrete
    gumbel: true

    param_ling: false
    param_task: true

    encode_ling: 0 # 0.01
    decode_ling: 0 # 0.01

  critic:
    type: linear
    by_task: true

objective:
  discount: 0.9
  entropy_bonus: 0.01
  step_size: 0.001
  n_train_batch: 4000

trainer: 
  name: CurriculumTrainer
  name: ImitationTrainer
  max_rollout_len: 100
  n_update: 100
  n_rollout_batch: 100
  parallel: 4
  log_each_task: false
  resample_every: 5
  switch_iter: 10000

#trainer:
#  name: RlLabTrainer
#  #algo: TRPO
#  algo: VPG
#  max_rollout_len: 100
#  n_iters: 10000
