name: minicraft_ling
load: minicraft_ling
train: true
eval: true

world: 
  name: Minicraft2World
  train_fold: train
  test_fold: val

guide:
  name: SketchGuide

model: 
  name: ReprModel
  intrinsic_bonus: 0
  actor:
    n_hidden: [64, 64]
    ret_bias: 0

  controller:
    n_embed: 50
    embeddings: "data/embeddings.txt"
    train_embeddings: false
    param_ling: true
    param_task: false

  critic:
    type: linear
    by_task: true

objective:
  discount: 0.9
  #step_size: 0.01
  step_size: 0.001
  entropy_bonus: 0.001
  n_train_batch: 10000

trainer:
  #name: RlLabTrainer
  #algo: VPG
  name: CurriculumTrainer 
  max_rollout_len: 100
  n_iters: 10000
  n_rollout_batch: 100
  n_update: 50
  resample_every: 1
  switch_iter: 0
  log_each_task: false
