name: shurdlurn_ling
load: shurdlurn_ling
train: true
eval: true

world: 
  name: ShurdlurnWorld
  train_fold: train
  test_fold: val

model: 
  name: ReprModel
  intrinsic_bonus: 0
  actor:
    n_hidden: [64, 64]
    ret_bias: 0

  controller:
    n_hidden: 128
    n_embed: 64
    param_ling: true
    param_task: false
    encode_ling: 0
    decode_ling: 0

  critic:
    type: linear
    by_task: true

objective:
  discount: 0.9
  step_size: 0.01
  entropy_bonus: 0.01
  n_train_batch: 1000

trainer:
  name: ImitationTrainer
  max_rollout_len: 100
  n_iters: 10000
  n_rollout_batch: 100
  n_update: 100
  resample_every: 5
  switch_iter: 10000
  log_each_task: false
